### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by davetcoleman** [ttk592/spline#2]
When running `make` in the examples folder I get:

```
g++ -I../../alglib/src -I../src -O2 -DNDEBUG -Wall -c interpol_alglib.cpp -o interpol_alglib.o
interpol_alglib.cpp:4:37: fatal error: interpolation.h: No such file or directory
 #include "interpolation.h" // alglib
```

Looks like there is a missing file from alglib - perhaps document this better?

**Comment by ttk592** [comment]
Thanks, yes alglib is needed for a few examples. The Makefile now checks if `ALGLIB` points to the correct path and aborts otherwise. Readme.md updated as well.
